name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  NODE_VERSION: 14.x

jobs:
  lint_and_test:
    if: "!(github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')"
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Run unit tests
        run: |
          npm run test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
